### ISSUE TITLE
[Suggestion] Show names with _

### ISSUE THREAD

**Issue by SeDark** [TownyAdvanced/Towny#2891]
Currently if there is a user that is called "User_" it shows it as "User ", and it creates a lot of confusion, I suggest that when executing /p show the _

**Comment by LlmDl** [comment]
Can you point out a list of places this appears? I'm guessing the /res {name} screen is one.

**Comment by SeDark** [comment]
/res {name}
/town {name} Both in the name of a city and in the list of residents
When you walk in a user's plot with _
/plot perm

I imagine that in the menus of nations it also happens but I don't use nations.

**Comment by LlmDl** [comment]
Fixed as of 0.92.0.11

**Comment by Segysmundo** [comment]
Hi, I'm not sure if you did it intentionally or not but you missed a few: h[ere](https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/TownyFormatter.java#L573)

**Comment by LlmDl** [comment]
That return statement won't be reached if it's a Resident object.

**Comment by Segysmundo** [comment]
I mean starting from that line, there are a few more down from there.

**Comment by LlmDl** [comment]
The ticket is for residents' names only, we intentionally parse out the _ in town and nation names.

**Comment by Segysmundo** [comment]
'Aight thnx for the info.
