### ISSUE TITLE
Bug: Buckets placing liquids inside of claims

### ISSUE THREAD

**Issue by silverwolfg11** [TownyAdvanced/Towny#3013]
BUG: Clicking on a water bucket on a block in the wild will empty the bucket inside a town claim. Sorry if this a bad explanation; I'll try to hopefully explain it in detail so it will make sense. 

I also apologize if this is a duplicate issue,

Basically, when a player right clicks a water bucket on a block not inside a town claim (that block is in the wild), it allows them to empty out the water bucket inside the town claim. I have verified that ItemUse and even Switch is disabled within the claim. 

### What steps will reproduce the problem?
1. Stand on a border of a town claim. Make sure to be standing inside the claim
2. Have a one-block wall (made out of any material) that is right outside the claim
3. Standing in the town claim, right click with a water bucket (and I assume this would also apply to lava buckets as well) on the one-block wall that is outside the claim. 
4. It should place the water inside the town claim, but it won't allow you to pick up the water.

### What is the expected output?
The expected output is that the water bucket should be cancelled and not place water within the claim

### What is your Towny version?
I believe I have the latest 1.12 Towny (so version 0.92), however the Towny Config says it's version  0.91.4.15. I did update towny recently (like a day ago) and this bug still persisted.

### What is your spigot/craftbukkit version?
API Version: 1.12.2-R0.1-SNAPSHOT. CraftBukkit: git-Spigot-eb3d921-2b93d83

### Config Files:
Towny Config: https://pastebin.com/Q9XW1c1T
Towny Permissions: https://pastebin.com/7AhuX62f

Please let me know if any more information is need!

**Comment by silverwolfg11** [comment]
Thank you for the response! I had no idea that it was fixed, my apologies.

**Comment by LlmDl** [comment]
It wasn't fixed until you made a ticket, so thanks for making the ticket.
