### ISSUE TITLE
Can claim plot next to other town when town the claiming town doesn't have any claimed plots

### ISSUE THREAD

**Issue by Hugo5000** [TownyAdvanced/Towny#4231]
### What steps will reproduce the problem?
1. create a town
2. do /t unclaim all
3. go next to another towns owned plot
4. do /t claim
5. you have claimed a plot directly next to another town

### What is the expected output?
1. an error that its to close to another town to claim

### What is your Towny version?
Towny version: 0.96.2.9

### What is your spigot/craftbukkit version?
Paper 128 1.16.1

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : default config / https://pastebin.com/NPjFxbkB
3. Your townyperms.yml : default perms / https://pastebin.com/rZ577K2T
4. Your log's error : none

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by silverwolfg11** [comment]
Yeah we are aware of the bug.  #4228 should fix that.

**Comment by Hugo5000** [comment]
okay thank you

**Comment by Hugo5000** [comment]
wait maybe I should keep this open just because it isnt resolved
