### ISSUE TITLE
Towny does not regenerate chunks below 0 depth on unclaim or unlock chests below 0 depth on unclaim.

### ISSUE THREAD

**Issue by PirateSoftware** [TownyAdvanced/Towny#6549]
### What steps will reproduce the problem?

1. Create a new town in any towny world.
2. Dig down to bedrock over the entire chunk claimed.
3. Unclaim the chunk.
---> The chunk will regenerate everything above 0 depth normally and will not regenerate anything below this.
---> The chunk will not unlock LWC chests below 0 even when LWC cleanup:townRuin is set to True

### What is the expected output?

Regeneration occurs down to bedrock and all chests unlock appropriately.

### Towny version

0.98.6.12

### Server version

1.18.2 Paper

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:
3. Your townyperms.yml:
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
I thought I fixed this a while back and you skipped the form.

**Comment by PirateSoftware** [comment]
Towny Config: https://pastebin.com/G90a0mVe
LWC Config: https://pastebin.com/DUfxEABD

**Comment by PirateSoftware** [comment]
> I thought I fixed this a while back and you skipped the form.

On the live server just now we had it fail unlocking all chests below 0 using version 0.98.6.12
Retesting plot regeneration now, will update the bug report if plot regeneration is working correctly.

**Comment by PirateSoftware** [comment]
This is still absolutely not regenerating blocks below 0 depth.
Got it live on stream currently.

**Comment by PirateSoftware** [comment]
Could this be happening because these towns were made before you made that fix?
What version was this fixed in?

**Comment by LlmDl** [comment]
Yes it could be from snapshots made before the fix.

Still missing the startup and other files from the form. 

https://github.com/TownyAdvanced/Towny#a-special-message-from-llmdl-precedes-the-normal-readme-

**Comment by PirateSoftware** [comment]
Looks like newly made plots work perfectly.
Definitely a snapshot issue made from before the fix.
Sorry for the non-valuable report!

**Comment by Tekh-ops** [comment]
forsen

**Comment by JR-Wiederkehr** [comment]
> lol what a fraud

Dude actually went through Jason's github page to troll because he thought he was special lmfao

**Comment by JR-Wiederkehr** [comment]
> > > lol what a fraud
> > 
> > 
> > Dude actually went through Jason's github page to troll because he thought he was special lmfao
> 
> "SWOSU" 😭😭🤣

You're making fun of me for attending University? That's an odd tactic.

**Comment by PramaYudhistira** [comment]
> > > > lol what a fraud
> > > 
> > > 
> > > Dude actually went through Jason's github page to troll because he thought he was special lmfao
> > 
> > 
> > "SWOSU" 😭😭🤣
> 
> You're making fun of me for attending University? That's an odd tactic.
yeah i am
<img width="1049" height="391" alt="Image" src="https://github.com/user-attachments/assets/5ec8c665-cae1-41e4-9a21-9d5236a23071" />

**Comment by JR-Wiederkehr** [comment]
> > > > > lol what a fraud
> > > > 
> > > > 
> > > > Dude actually went through Jason's github page to troll because he thought he was special lmfao
> > > 
> > > 
> > > "SWOSU" 😭😭🤣
> > 
> > 
> > You're making fun of me for attending University? That's an odd tactic.
> 
> yeah i am <img alt="Image" width="1049" height="391" src="https://private-user-images.githubusercontent.com/109050315/470155554-5ec8c665-cae1-41e4-9a21-9d5236a23071.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMzNDA0OTgsIm5iZiI6MTc1MzM0MDE5OCwicGF0aCI6Ii8xMDkwNTAzMTUvNDcwMTU1NTU0LTVlYzhjNjY1LWNhZTEtNDFlNC05YTIxLTlkNTIzNmEyMzA3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcyNFQwNjU2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWUzMmVjOGFlNjM3MjM4Mjc0NjYzZjA0YWFiODFjZDI4MzkyYWE1ZWJhYmM0NWM4M2MxODhmZGRlNTBiZTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aibPv55eMg05_pofXgkK1hGZnE5eR-oiY6BjAWTCG_w">

What's your point? I got a full ride for my 34 ACT, and they have one of the best IT programs in the state? (Right behind OSU IT, which I didn't apply to because I got the scholarship)

**Comment by PramaYudhistira** [comment]
> > > > > > lol what a fraud
> > > > > 
> > > > > 
> > > > > Dude actually went through Jason's github page to troll because he thought he was special lmfao
> > > > 
> > > > 
> > > > "SWOSU" 😭😭🤣
> > > 
> > > 
> > > You're making fun of me for attending University? That's an odd tactic.
> > 
> > 
> > yeah i am <img alt="Image" width="1049" height="391" src="https://private-user-images.githubusercontent.com/109050315/470155554-5ec8c665-cae1-41e4-9a21-9d5236a23071.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMzNDA0OTgsIm5iZiI6MTc1MzM0MDE5OCwicGF0aCI6Ii8xMDkwNTAzMTUvNDcwMTU1NTU0LTVlYzhjNjY1LWNhZTEtNDFlNC05YTIxLTlkNTIzNmEyMzA3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcyNFQwNjU2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWUzMmVjOGFlNjM3MjM4Mjc0NjYzZjA0YWFiODFjZDI4MzkyYWE1ZWJhYmM0NWM4M2MxODhmZGRlNTBiZTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aibPv55eMg05_pofXgkK1hGZnE5eR-oiY6BjAWTCG_w">
> 
> What's your point? I got a full ride for my 34 ACT, and they have one of the best IT programs in the state? (Right behind OSU IT, which I didn't apply to because I got the scholarship)

woahhhhhhh one of the best IT programs in Oklahoma? 

<img width="751" height="383" alt="Image" src="https://github.com/user-attachments/assets/6d7591b9-0f2a-452c-85f6-9a3db9de540c" />

**Comment by JR-Wiederkehr** [comment]
> > Lmao, someone can't lookup trade proficiencies apparently. "One of the best IT programs in Oklahoma" generally means top 10 in the nation, Oklahoma is known for its IT education, as seen through FIRST Robotics, BPA, and SkillsUSA, where Oklahoma is ~30% of the competitors
> 
> don't forget to add that 100% acceptance rate stat along with those other meaningless ones 👍

Uhuh, sure bud. Lemme know when you actually contribute something to society instead of just wasting oxygen trolling on dead forums lmfao. Got nothing better to do?

**Comment by PramaYudhistira** [comment]
> > don't forget to add that 100% acceptance rate stat along with those other meaningless ones 👍
> 
> Uhuh, sure bud. Lemme know when you actually contribute something to society instead of just wasting oxygen trolling on dead forums lmfao. Got nothing better to do?

im not so insecure that i have to list my stats that i go to a 100% acceptance rate school 🤣🤣 we are both on the same forum "bud" and im not even gonna bother telling you how i don't not contribute to society cuz unlike u im not insecure

**Comment by JR-Wiederkehr** [comment]
> > > don't forget to add that 100% acceptance rate stat along with those other meaningless ones 👍
> > 
> > 
> > Uhuh, sure bud. Lemme know when you actually contribute something to society instead of just wasting oxygen trolling on dead forums lmfao. Got nothing better to do?
> 
> im not so insecure that i have to list my stats that i go to a 100% acceptance rate school 🤣🤣 we are both on the same forum "bud" and im not even gonna bother telling you how i don't not contribute to society cuz unlike u im not insecure

... How dare the account linked to my school mention my school, how insecure of me lmfao, get a life

**Comment by PramaYudhistira** [comment]
> ... How dare the account linked to my school mention my school, how insecure of me lmfao, get a life

lol hop off Jason's meat, riding it with no license is illegal. take your own advice since we are both in the same forum, and you are spending more time than i am figuring out responses with u editing ur comments like 5 times to make sure u can regurgitate those meaningless stats 🤣🤣😭😭 

"SWOSU" 😆😆

**Comment by PramaYudhistira** [comment]
> What? Jason can be a piece of shit, but I still don't waste my time trolling lol

yet you are wasting ur time to respond to my comment thats 2 weeks old, and you are continuously replying to my comments 😭😭 you are so dumb you dont even see this. at least i admit im wasting my time
